import { Colors } from '@/constants/theme';
import { StyleSheet } from 'react-native';

type AppTheme = (typeof Colors)[keyof typeof Colors];

const createHomeStyles = (theme: AppTheme) => StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bell: {
    fontSize: 22,
    color: theme.text,
  },
  logo: {
    fontSize: 28,
    fontWeight: '800',
    color: theme.text,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: theme.text,
    textAlign: 'right',
    marginTop: 24,
  },
  subtitle: {
    fontSize: 13,
    color: theme.textSecondary,
    textAlign: 'right',
    marginTop: 4,
    marginBottom: 18,
  },
  row: {
    flexDirection: 'row-reverse',
    gap: 14,
    marginBottom: 16,
  },
smallCard: {
  flex: 1,
  minHeight: 250,
  backgroundColor: theme.surface,
  borderRadius: 22,
  padding: 16,
  shadowColor: theme.shadow,
  shadowOpacity: 0.08,
  shadowRadius: 12,
  elevation: 3,
  justifyContent: 'space-between',
},
  cardTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: theme.text,
    textAlign: 'right',
    marginBottom: 8,
  },
  timeText: {
    fontSize: 13,
    color: theme.textSecondary,
    textAlign: 'right',
    marginBottom: 8,
  },
progressCircle: {
  width: 86,
  height: 86,
  alignSelf: 'center',
  alignItems: 'center',
  justifyContent: 'center',
  marginTop: 2,
},

progressPercent: {
  position: 'absolute',
  fontSize: 20,
  color: theme.accentDark,
  fontWeight: '900',
},
  progressLabel: {
    fontSize: 12,
    color: theme.textSecondary,
    textAlign: 'center',
    marginTop: 8,
    fontWeight: '700',
  },
  goalTitle: {
    fontSize: 14,
    color: theme.text,
    textAlign: 'right',
    fontWeight: '700',
    marginTop: 8,
  },
  goalProgress: {
    fontSize: 12,
    color: theme.textSecondary,
    textAlign: 'right',
    marginTop: 5,
    marginBottom: 12,
  },
  goalBar: {
    height: 9,
    backgroundColor: theme.border,
    borderRadius: 99,
    overflow: 'hidden',
    marginBottom: 16,
  },
  goalBarFill: {
    width: '75%',
    height: '100%',
    backgroundColor: theme.accent,
    borderRadius: 99,
  },
  greenButton: {
    backgroundColor: theme.accent,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  buttonText: {
    color: theme.accentText,
    fontWeight: '700',
    fontSize: 13,
  },
  wideCard: {
    backgroundColor: theme.backgroundSelected,
    borderRadius: 24,
    padding: 20,
    minHeight: 250,
    shadowColor: theme.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    marginBottom: 22,
  },
  dots: {
    position: 'absolute',
    left: 18,
    top: 12,
    fontSize: 22,
    color: theme.textSecondary,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: theme.text,
    textAlign: 'right',
    marginBottom: 6,
  },
  cardText: {
    fontSize: 14,
    color: theme.textSecondary,
    textAlign: 'right',
    marginBottom: 14,
    lineHeight: 20,
  },
  taskList: {
    gap: 9,
    marginBottom: 18,
  },
  taskRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 9,
  },
  taskCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    textAlign: 'center',
    lineHeight: 22,
    color: theme.textSecondary,
    fontWeight: '800',
  },
  taskCheckDone: {
    backgroundColor: theme.accent,
    color: theme.accentText,
  },
  taskText: {
    flex: 1,
    fontSize: 13,
    color: theme.text,
    textAlign: 'right',
    fontWeight: '600',
  },
  taskTextDone: {
    color: theme.text,
  },
  fullButton: {
    backgroundColor: theme.accent,
    borderRadius: 13,
    paddingVertical: 14,
    alignItems: 'center',
  },
  sectionHeader: {
    fontSize: 20,
    fontWeight: '800',
    color: theme.text,
    textAlign: 'right',
    marginBottom: 12,
  },
  bottomCard: {
    flex: 1,
    backgroundColor: theme.surface,
    borderRadius: 20,
    padding: 18,
    minHeight: 132,
    shadowColor: theme.shadow,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  bottomTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: theme.text,
    textAlign: 'right',
  },
  bottomText: {
    fontSize: 13,
    color: theme.textSecondary,
    textAlign: 'right',
    marginTop: 6,
    lineHeight: 18,
  },
  checkinButton: {
    marginTop: 14,
    backgroundColor: theme.accent,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  checkinButtonText: {
    color: theme.accentText,
    fontSize: 13,
    fontWeight: '800',
  },
  reserveBadge: {
    marginTop: 14,
    alignSelf: 'flex-end',
    backgroundColor: theme.surfaceMuted,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  reserveBadgeText: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: '800',
  },
  floatingButton: {
    position: 'absolute',
    bottom: 48,
    alignSelf: 'center',
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: theme.accent,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 5,
    zIndex: 10,
  },
  floatingText: {
    color: theme.accentText,
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 34,
  },
  navbar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 74,
    backgroundColor: theme.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    flexDirection: 'row-reverse',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: 10,
  },
  navItem: {
    fontSize: 24,
    color: theme.textSecondary,
  },
  navActive: {
    fontSize: 25,
    color: theme.accentDark,
    fontWeight: '800',
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 58,
    paddingBottom: 120,
  },

  taskTitleButton: {
    flex: 1,
  },

  removeTaskText: {
    color: theme.danger,
    fontWeight: '700',
  },

  addTaskArea: {
    marginTop: 14,
  },

  taskInput: {
    backgroundColor: theme.input,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: theme.text,
    marginBottom: 10,
  },
  root: {
    flex: 1,
    backgroundColor: theme.background,
  },
  finishDayButton: {
    marginTop: 10,
    backgroundColor: theme.surface,
    borderRadius: 13,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.accent,
  },

  finishDayText: {
    color: theme.accentDark,
    fontWeight: '900',
    fontSize: 13,
  },
  saveMessage: {
    marginTop: 10,
    color: theme.accentDark,
    fontWeight: '800',
    fontSize: 13,
    textAlign: 'center',
  },
  myDaysButton: {
  marginTop: 10,
  backgroundColor: theme.surfaceMuted,
  borderRadius: 12,
  paddingVertical: 9,
  alignItems: 'center',
},

myDaysButtonText: {
  color: theme.accentDark,
  fontSize: 12,
  fontWeight: '900',
},
bottomButton: {
  marginTop: 'auto',
},
workoutQuestionCard: {
  marginTop: 10,
  backgroundColor: theme.surface,
  borderRadius: 13,
  padding: 14,
  borderWidth: 1,
  borderColor: theme.accent,
},

workoutQuestionTitle: {
  color: theme.text,
  fontWeight: '800',
  fontSize: 13,
  textAlign: 'right',
  marginBottom: 10,
},

workoutQuestionRow: {
  flexDirection: 'row-reverse',
  gap: 10,
},

workoutYesButton: {
  flex: 1,
  backgroundColor: theme.accent,
  borderRadius: 12,
  paddingVertical: 12,
  alignItems: 'center',
},

workoutNoButton: {
  flex: 1,
  backgroundColor: theme.surface,
  borderRadius: 12,
  paddingVertical: 12,
  alignItems: 'center',
  borderWidth: 1,
  borderColor: theme.accent,
},
streakContainer: {
  marginTop: 10,
  backgroundColor: theme.surface,
  borderRadius: 10,
  paddingVertical: 8,
  paddingHorizontal: 12,
},

streakText: {
  textAlign: 'center',
  color: theme.accentDark,
  fontWeight: '800',
  fontSize: 13,
},
streakDivider: {
  height: 1,
  backgroundColor: theme.border,
  marginVertical: 10,
},
});
export default createHomeStyles;
